python3: can't open file '/afs/cern.ch/work/t/tcritchl/FCCAnalyses_local/xgboost/new_variables_training/training_macro.py': [Errno 2] No such file or directory
